name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"


    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - run: python -m pip install --upgrade pip

      - run: pip install -e ".[dev]"

      - name: Run test suite
        run: pytest --pyargs approxkit

      - name: Ruff check
        if: matrix.python-version == '3.13'
        run: |
          ruff --version
          ruff check .

      - name: Type check
        if: matrix.python-version == '3.13'
        run: mypy src

      - name: Build package and validate metadata
        if: matrix.python-version == '3.13'
        run:  |
          python -m build
          twine check dist/*

      - name: Coverage
        if: matrix.python-version == '3.13'
        run: |
          pytest --pyargs approxkit \
            --cov=approxkit \
            --cov-branch \
            --cov-report=xml

      - name: Upload results to Codecov
        if: matrix.python-version == '3.13'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: pbrod/approxkit